name: gimrari
favicon: null
layout_spectrum: 0.6374575409572572
typography_spectrum: 0.32050160714425147
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7111373469233513
  lightness: 0.8678043291438371
  saturation: 0.5909109704662114
  rhythmicContrast: 0.1045592469163239
purpose: []
